name: periMI
channels:
  - conda-forge
dependencies:
  - python=3.12.10
  - numpy=2.2.6
  - pandas=2.3.0
  - scipy=1.16.0
  - scikit-image=0.25.2
  - openpyxl=3.1.5
  - tifffile=2025.6.11
  - pip
  - pip:
      - napari==0.6.2
      - napari-skimage==0.5.0

      