name: periMI
channels:
  - conda-forge
dependencies:
  - python>=3.12.10,<3.13
  - jupyterlab>=4.4,<5.0
  - pandas>=2.3.0,<2.4
  - tifffile=2025.6.11
  - scipy=1.16.0
  - scikit-image=0.25.2
  - openpyxl=3.1.5
  - pip
  - pip:
      - napari==0.6.2
      